name: VPS-Pinggy
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Setup User
        run: |
          sudo useradd -m runneruser
          echo 'runneruser:admin@123' | sudo chpasswd
          sudo usermod -aG sudo runneruser
          echo "USER=runneruser" >> $GITHUB_ENV
          echo "PASS=admin@123" >> $GITHUB_ENV

      - name: Install SSH Server
        run: |
          sudo apt-get update -y
          sudo apt-get install -y openssh-server
          sudo systemctl enable ssh
          sudo systemctl start ssh

      - name: Connect Pinggy Tunnel
        run: |
          echo "===================================="
          echo "     VPS SSH CONNECTION INFO         "
          echo "------------------------------------"
          echo "Username : $USER"
          echo "Password : $PASS"
          echo "------------------------------------"
          echo "سيتم توليد رابط الاتصال الآن ..."
          echo "===================================="

          while true; do
            # شغل النفق واطبع رابط الاتصال الجاهز
            ssh -p 443 -R0:localhost:22 \
                -o StrictHostKeyChecking=no \
                -o ServerAliveInterval=30 \
                ${{ secrets.PINGGY_AUTH }}@free.pinggy.io 2>&1 | tee pinggy.log || true

            # إذا ظهر رابط ssh -p ... اطبعه مع اليوزر والباسورد
            if grep -q "ssh -p" pinggy.log; then
              TUNNEL_CMD=$(grep "ssh -p" pinggy.log | tail -n 1)
              echo "===================================="
              echo " انسخ السطر التالي للاتصال مباشرة:"
              echo ""
              echo "  $TUNNEL_CMD -l $USER"
              echo "  Password: $PASS"
              echo ""
              echo "===================================="
            fi

            sleep 10
          done
