name: VPS-Pinggy
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Setup User
        run: |
          sudo useradd -m runneruser
          echo 'runneruser:admin@123' | sudo chpasswd
          sudo usermod -aG sudo runneruser
          echo "USER=runneruser" >> $GITHUB_ENV
          echo "PASS=admin@123" >> $GITHUB_ENV

      - name: Install SSH Server
        run: |
          sudo apt-get update -y
          sudo apt-get install -y openssh-server
          sudo systemctl enable ssh
          sudo systemctl start ssh

      - name: Connect Pinggy Tunnel
        run: |
          echo "===================================="
          echo "     VPS SSH CONNECTION INFO        "
          echo "------------------------------------"
          echo "Username : $USER"
          echo "Password : $PASS"
          echo "------------------------------------"
          echo "انتظر توليد رابط الاتصال ..."
          echo "===================================="

          while true; do
            ssh -p 443 -R0:localhost:22 \
                -o StrictHostKeyChecking=no \
                -o ServerAliveInterval=30 \
                ${{ secrets.PINGGY_AUTH }}@free.pinggy.io || true
            sleep 10
          done
