name: VPS-Pinggy
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Setup User
        run: |
          sudo useradd -m runneruser
          echo 'runneruser:admin@123' | sudo chpasswd
          sudo usermod -aG sudo runneruser
          echo "USER=runneruser" >> $GITHUB_ENV
          echo "PASS=admin@123" >> $GITHUB_ENV

      - name: Install SSH Server
        run: |
          sudo apt-get update -y
          sudo apt-get install -y openssh-server
          sudo systemctl enable ssh
          sudo systemctl start ssh

      - name: Connect Pinggy Tunnel
        run: |
          echo "===================================="
          echo "     VPS SSH CONNECTION INFO         "
          echo "------------------------------------"
          echo "Username : $USER"
          echo "Password : $PASS"
          echo "------------------------------------"
          echo "انتظر توليد رابط الاتصال ..."
          echo "===================================="

          ssh -p 443 -R0:localhost:22 \
              -o StrictHostKeyChecking=no \
              -o ServerAliveInterval=30 \
              ${{ secrets.PINGGY_AUTH }}@free.pinggy.io 2>&1 | tee tunnel.log &

          sleep 15

          # التقاط السطر الي يحتوي على ssh -p
          if grep -q "ssh -p" tunnel.log; then
            TUNNEL_CMD=$(grep "ssh -p" tunnel.log | head -n 1)
            echo ""
            echo "========= READY TO CONNECT ========="
            echo " $TUNNEL_CMD -l $USER"
            echo " Password: $PASS"
            echo "===================================="
          else
            echo "⚠️ ما قدر يجيب رابط SSH من Pinggy"
          fi

          # حافظ على الجلسة شغالة
          tail -f /dev/null
